kind = "web"
previewPath = "/"
title = "IR Search Engine"
version = "1.0.0"
id = "artifacts/ir-search"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19324

[services.development]
run = "pnpm --filter @workspace/ir-search run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ir-search", "run", "build" ]
publicDir = "artifacts/ir-search/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19324"
BASE_PATH = "/"
